version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # MinIO console
      - "9001:9001" # MinIO admin console
    environment:
      MINIO_ROOT_USER: minioadmin # Default username
      MINIO_ROOT_PASSWORD: minioadmin # Default password
    volumes:
      - minio_data:/data # Persistent storage
    command: server /data --console-address ":9001"

volumes:
  minio_data:
